### ISSUE TITLE
Unexpected close

### ISSUE THREAD

**Issue by denic** [OpusCapita/event-client#18]
While debugging, blocking the process continuation a connected event client will throw an unhandled exception. If possible catch:

```
main_1           | {"serviceName":"archive","serviceInstanceId":0,"correlationId":null,"userId":null,"requestUri":null,"uniqueId":"6cd4a06a237210542e174ed2665cc674","timestamp":"2018-08-23T07:28:47.988Z","level":"info","message":"Current connectTryCount: 1"}
main_1           | {"serviceName":"archive","serviceInstanceId":0,"correlationId":null,"userId":null,"requestUri":null,"uniqueId":"6cd4a06a237210542e174ed2665cc674","timestamp":"2018-08-23T07:28:47.988Z","level":"info","message":"Trying to connect to 172.18.0.3:5672..."}
main_1           | {"serviceName":"archive","serviceInstanceId":0,"correlationId":null,"userId":null,"requestUri":null,"uniqueId":"6cd4a06a237210542e174ed2665cc674","timestamp":"2018-08-23T07:28:47.995Z","level":"warn","message":"AmqpConnection: Connection went to ERROR state Error: Unexpected close\n    at succeed (/home/node/archive/node_modules/amqplib/lib/connection.js:271:13)\n    at onOpenOk (/home/node/archive/node_modules/amqplib/lib/connection.js:253:5)\n    at /home/node/archive/node_modules/amqplib/lib/connection.js:166:32\n    at /home/node/archive/node_modules/amqplib/lib/connection.js:160:12\n    at Socket.recv (/home/node/archive/node_modules/amqplib/lib/connection.js:498:12)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:106:13)\n    at Socket.emit (events.js:208:7)\n    at emitReadable_ (_stream_readable.js:513:10)\n    at emitReadable (_stream_readable.js:507:7)\n    at addChunk (_stream_readable.js:274:7)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:597:20)"}
main_1           | {"serviceName":"archive","serviceInstanceId":0,"correlationId":null,"userId":null,"requestUri":null,"uniqueId":"6cd4a06a237210542e174ed2665cc674","timestamp":"2018-08-23T07:28:47.995Z","level":"info","message":"AmqpChannel#onChannelClose: onChannelClose Handler triggered ... a channel has been closed. "}
main_1           | {"serviceName":"archive","serviceInstanceId":0,"correlationId":null,"userId":null,"requestUri":null,"uniqueId":"6cd4a06a237210542e174ed2665cc674","timestamp":"2018-08-23T07:28:47.995Z","level":"warn","message":"AmqpConnection: Connection went to CLOSED state Error: Unexpected close\n    at succeed (/home/node/archive/node_modules/amqplib/lib/connection.js:271:13)\n    at onOpenOk (/home/node/archive/node_modules/amqplib/lib/connection.js:253:5)\n    at /home/node/archive/node_modules/amqplib/lib/connection.js:166:32\n    at /home/node/archive/node_modules/amqplib/lib/connection.js:160:12\n    at Socket.recv (/home/node/archive/node_modules/amqplib/lib/connection.js:498:12)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:106:13)\n    at Socket.emit (events.js:208:7)\n    at emitReadable_ (_stream_readable.js:513:10)\n    at emitReadable (_stream_readable.js:507:7)\n    at addChunk (_stream_readable.js:274:7)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:597:20)"}
main_1           | events.js:183
main_1           |       throw er; // Unhandled 'error' event
main_1           |       ^
main_1           | 
main_1           | Error: Unexpected close
main_1           |     at succeed (/home/node/archive/node_modules/amqplib/lib/connection.js:271:13)
main_1           |     at onOpenOk (/home/node/archive/node_modules/amqplib/lib/connection.js:253:5)
main_1           |     at /home/node/archive/node_modules/amqplib/lib/connection.js:166:32
main_1           |     at /home/node/archive/node_modules/amqplib/lib/connection.js:160:12
main_1           |     at Socket.recv (/home/node/archive/node_modules/amqplib/lib/connection.js:498:12)
main_1           | {"serviceName":"archive","serviceInstanceId":0,"correlationId":null,"userId":null,"requestUri":null,"uniqueId":"6cd4a06a237210542e174ed2665cc674","timestamp":"2018-08-23T07:28:47.996Z","level":"info","message":"Current connectTryCount: 1"}
main_1           | {"serviceName":"archive","serviceInstanceId":0,"correlationId":null,"userId":null,"requestUri":null,"uniqueId":"6cd4a06a237210542e174ed2665cc674","timestamp":"2018-08-23T07:28:47.996Z","level":"info","message":"Trying to connect to 172.18.0.3:5672..."}
main_1           | {"serviceName":"archive","serviceInstanceId":0,"correlationId":null,"userId":null,"requestUri":null,"uniqueId":"6cd4a06a237210542e174ed2665cc674","timestamp":"2018-08-23T07:28:47.997Z","level":"warn","message":"AmqpConnection: Connection went to ERROR state Error: Unexpected close\n    at succeed (/home/node/archive/node_modules/amqplib/lib/connection.js:271:13)\n    at onOpenOk (/home/node/archive/node_modules/amqplib/lib/connection.js:253:5)\n    at /home/node/archive/node_modules/amqplib/lib/connection.js:166:32\n    at /home/node/archive/node_modules/amqplib/lib/connection.js:160:12\n    at Socket.recv (/home/node/archive/node_modules/amqplib/lib/connection.js:498:12)\n    at Object.onceWrapper (events.js:313:30)\n    at emitNone (events.js:106:13)\n    at Socket.emit (events.js:208:7)\n    at emitReadable_ (_stream_readable.js:513:10)\n    at emitReadable (_stream_readable.js:507:7)\n    at addChunk (_stream_readable.js:274:7)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at TCP.onread (net.js:597:20)"}
main_1           |     at Object.onceWrapper (events.js:313:30)
main_1           |     at emitNone (events.js:106:13)
main_1           |     at Socket.emit (events.js:208:7)
main_1           |     at emitReadable_ (_stream_readable.js:513:10)
main_1           |     at emitReadable (_stream_readable.js:507:7)
main_1           |     at addChunk (_stream_readable.js:274:7)
main_1           |     at readableAddChunk (_stream_readable.js:250:11)
main_1           |     at Socket.Readable.push (_stream_readable.js:208:10)
main_1           |     at TCP.onread (net.js:597:20)

```

**Comment by maciej-wakula-opuscapita** [comment]
This is probably an expected scenario. Likely the developer locked node thread for 12-15 seconds and RabbitMQ closed DEAD connection...
